<a href="https://colab.research.google.com/github/soumya0422/fds/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy program to get the Numpy version.
import numpy as np
print (np.__version__);

1.25.2


In [ ]:
#NumPy program to test whether none of the elements of a given array are zero.
import numpy as np
x=np.array([1,2,0,6]);
print(np.all(x));

False


In [5]:
#NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
import pandas as pd
p=np.array([3,4]);
q=np.array([7,8]);
print(np.greater(p,q));
print(np.greater_equal(p,q));
print(np.less(p,q));
print(np.less_equal(p,q));

[False False]
[False False]
[ True  True]
[ True  True]


In [ ]:
#NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
import pandas as pd
arr1=[1,7,13,105];
arr=np.array(arr1);
print("memory size of array:"+str(arr.itemsize*arr.size));
print(arr);

memory size of array:32
[  1   7  13 105]


In [ ]:
#NumPy program to create an array of integers from 30 to 70.
import numpy as np
b=[];
for j in range(30,71):
  n=j;
  b.append(n);
arr=np.array(b);
print(arr);

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
#NumPy program to create an array of all even integers from 30 to 70.
import numpy as np
a=[];
for i in range(15,36):
  m=2*i;
  a.append(m);
arr=np.array(a);
print(arr);

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [4]:
#NumPy program to create a 3x3 identity matrix.
import numpy as np
i=np.identity(3);
print(i);
#NumPy program to create a 3X4 array and iterate over it.
a = np.arange(10,22).reshape((3, 4));
print("Original array:");
print(a);
print("Each element of the array is:");
for x in np.nditer(a):
  print(x,end=" ");

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 